export { default as RegistrationMail } from '@modules/http/accounts/tasks/RegistrationMailTask'
export { default as RecoveryMail } from '@modules/http/accounts/tasks/RecoveryMailTask'
export { default as WhitelistChangeEmail } from '@modules/http/saturn/tasks/WhitelistChangeEmailTask'
export { default as AppointmentReadyMail } from '@modules/http/player/tasks/email/AppointmentReadyMail'
export { default as AppointmentAlertMail } from '@modules/http/player/tasks/email/AppointmentAlertMail'
export { default as InterviewAppointment } from '@modules/http/player/tasks/schedule/AppointmentTask'
